import io
import logging
from typing import Dict, Any

logger = logging.getLogger('ats_resume_scorer')

try:
    from weasyprint import HTML
    WEASYPRINT_AVAILABLE = True
except Exception:
    WEASYPRINT_AVAILABLE = False


def _generate_reportlab_pdf(html_docs: Dict[str, str], analysis_data: Dict[str, Any] = None) -> bytes:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#0f172a'),
        spaceAfter=6,
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748b'),
        spaceAfter=15,
    )
    
    h2_style = ParagraphStyle(
        'SectionH2',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#1e293b'),
        spaceBefore=14,
        spaceAfter=8,
    )
    
    body_style = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor('#334155'),
    )

    score_val_style = ParagraphStyle(
        'ScoreVal',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=36,
        leading=40,
        alignment=1, # Center
    )

    score_interp_style = ParagraphStyle(
        'ScoreInterp',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#475569'),
        alignment=1, # Center
        spaceAfter=15,
    )

    elements = []

    # 1. Header
    elements.append(Paragraph("ATS RESUME ANALYSIS REPORT", title_style))
    elements.append(Paragraph("Generated by AI Resume ATS System • Automated Assessment", subtitle_style))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#cbd5e1'), spaceAfter=15))

    # Fallback data extraction if analysis_data not provided
    data = analysis_data or {}
    score = float(data.get('ATS_score', 0) or data.get('ats_score', 0))
    interpretation = data.get('interpretation', 'Evaluation completed.')

    score_color = colors.HexColor('#16a34a') if score >= 80 else (colors.HexColor('#d97706') if score >= 60 else colors.HexColor('#dc2626'))
    score_val_style.textColor = score_color

    # 2. Overall Score Display
    elements.append(Paragraph(f"{score:.0f} / 100", score_val_style))
    elements.append(Paragraph(f"<b>Overall Rating:</b> {interpretation}", score_interp_style))

    # 3. Component Scores Table
    elements.append(Paragraph("Component Score Breakdown", h2_style))
    
    cs = data.get('component_scores', {})
    if hasattr(cs, '__dict__'):
        cs = cs.__dict__
    elif not isinstance(cs, dict):
        cs = {}

    breakdown_data = [
        ["Evaluation Dimension", "Score Achieved", "Max Weight", "Status"],
        ["Formatting & Structure", f"{float(cs.get('formatting', 0)):.1f}", "20.0", "Pass" if float(cs.get('formatting', 0)) >= 14 else "Needs Work"],
        ["Keywords & Technical Skills", f"{float(cs.get('keywords', 0)):.1f}", "25.0", "Pass" if float(cs.get('keywords', 0)) >= 17 else "Needs Work"],
        ["Content Quality & Impact", f"{float(cs.get('content', 0)):.1f}", "25.0", "Pass" if float(cs.get('content', 0)) >= 17 else "Needs Work"],
        ["Skill Validation", f"{float(cs.get('skill_validation', 0)):.1f}", "15.0", "Pass" if float(cs.get('skill_validation', 0)) >= 10 else "Needs Work"],
        ["ATS Parsing Compatibility", f"{float(cs.get('ats_compatibility', 0)):.1f}", "15.0", "Pass" if float(cs.get('ats_compatibility', 0)) >= 10 else "Needs Work"],
    ]

    t = Table(breakdown_data, colWidths=[200, 100, 100, 130])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('ALIGN', (1, 0), (2, -1), 'CENTER'),
        ('ALIGN', (3, 0), (3, -1), 'CENTER'),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 15))

    # 4. Key Strengths
    strengths = data.get('strengths', [])
    if strengths:
        elements.append(Paragraph("Identified Strengths", h2_style))
        for s in strengths[:5]:
            elements.append(Paragraph(f"• <b>Strength:</b> {s}", body_style))
            elements.append(Spacer(1, 3))
        elements.append(Spacer(1, 10))

    # 5. Critical Issues & Recommendations
    detailed_fb = data.get('detailed_feedback', [])
    if detailed_fb:
        elements.append(Paragraph("Critical Feedback & Recommendations", h2_style))
        for idx, item in enumerate(detailed_fb[:5], 1):
            if hasattr(item, '__dict__'):
                item = item.__dict__
            title = item.get('issue_title', f'Issue #{idx}')
            expl = item.get('explanation', '')
            fix = item.get('how_to_fix', '')
            
            p_text = f"<b>{idx}. {title}</b><br/>"
            if expl:
                p_text += f"<i>Issue:</i> {expl}<br/>"
            if fix:
                p_text += f"<font color='#047857'><b>Actionable Fix:</b> {fix}</font>"
            
            elements.append(Paragraph(p_text, body_style))
            elements.append(Spacer(1, 6))

    # Footer notice
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#e2e8f0'), spaceAfter=8))
    elements.append(Paragraph("Confidential Evaluation • Built with FastAPI, Sentence-Transformers & Groq LLM", subtitle_style))

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


def generate_combined_pdf(html_docs: Dict[str, str], analysis_data: Dict[str, Any] = None) -> bytes:
    """
    Generate PDF report. Uses WeasyPrint if available;
    otherwise seamlessly falls back to pure Python ReportLab so PDF export NEVER fails!
    """
    if WEASYPRINT_AVAILABLE:
        try:
            documents = []
            for name, html_str in html_docs.items():
                doc = HTML(string=html_str).render()
                documents.append(doc)
            first_doc = documents[0]
            for other_doc in documents[1:]:
                for page in other_doc.pages:
                    first_doc.pages.append(page)
            return first_doc.write_pdf()
        except Exception as exc:
            logger.warning(f"WeasyPrint rendering failed ({exc}), falling back to ReportLab...")
    
    # Robust native Python ReportLab generation
    return _generate_reportlab_pdf(html_docs, analysis_data)